spring:
  mongodb:
    embedded:
      version: 5.0.6

  webflux:
    hiddenmethod:
      filter:
        enabled: true



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

#management:
#  endpoint:
#    health:
#      show-details: always

info:
  project:
    version: project.version@
  java:
    version: java.version@
  spring:
    framework:
      version: spring-framework.version@
    data:
      version: spring-data-bom.version@
